# Databases config file for PostgreSQL

- name: Databases | Make sure the PostgreSQL databases are present
  postgresql_db:
    name: "{{ item.name }}"
    encoding: "{{postgresql_encoding}}"
    lc_collate: "{{postgresql_locale}}"
    lc_ctype: "{{postgresql_locale}}"
    template: "template0"
    state: present
  with_items: postgresql_databases
  when: postgresql_databases|length > 0

- name: Databases | Add hstore to the databases with the requirement
  sudo: yes
  sudo_user: "{{postgresql_admin_user}}"
  shell: "psql {{item.name}} -c 'CREATE EXTENSION IF NOT EXISTS hstore;'"
  with_items: postgresql_databases
  when: "item.hstore is defined and item.hstore == 'yes'"

# Move clientadmin pg_dump file into place and restore database contents
#
# Note - improve this by using variables for the source and dest 
#        and again when used by restore?
#

- name: Databases | Move dump file for clientadmin from Mgr1 to db1
  copy: src=/data/dataStore/postgres/db-clientadmin-ppe-20150827-104116 dest=/var/lib/pgsql/9.4/backups/ owner=postgres

- name: Databases | Restore dump file for clientadmin
  sudo: yes
  sudo_user: postgres
  command: pg_restore -d clientadmin /var/lib/pgsql/9.4/backups/db-clientadmin-ppe-20150827-104116